### ISSUE TITLE
Website is looking ugly (css issues?)

### ISSUE THREAD

**Issue by darkmattercoder** [Bytewerk/spn-docker#2]
The website is looking not so good:

![image](https://user-images.githubusercontent.com/2217280/40278617-bbbc9ab8-5c34-11e8-9526-7d2825040643.png)

**Comment by cfr34k** [comment]
Hi, my first guess is that you are accessing the website as http://localhost:8080. If so, could you please try http://localhost:80 ?

The static files (including the CSS) for the website are served by nginx running in the proxy container on port 80, so they are not found when the website is accessed directly on port 8080.

**Comment by darkmattercoder** [comment]
You were right, it was the wrong port (8000), I did not notice the 80. It looks like it should now.
